# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\"%\n\x08Response\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\"*\n\x07Request\x12\x0e\n\x06\x63hukid\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\")\n\x13ServerSpeedResponse\x12\x12\n\nserver_mtu\x18\x01 \x01(\x03\"%\n\x12ServerSpeedRequest\x12\x0f\n\x07request\x18\x01 \x01(\x03\x32u\n\x0c\x46ileTransfer\x12&\n\rfile_transfer\x12\x08.Request\x1a\t.Response\"\x00\x12=\n\x0eServerResponse\x12\x13.ServerSpeedRequest\x1a\x14.ServerSpeedResponse\"\x00\x62\x06proto3')



_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_SERVERSPEEDRESPONSE = DESCRIPTOR.message_types_by_name['ServerSpeedResponse']
_SERVERSPEEDREQUEST = DESCRIPTOR.message_types_by_name['ServerSpeedRequest']
Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

ServerSpeedResponse = _reflection.GeneratedProtocolMessageType('ServerSpeedResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERSPEEDRESPONSE,
  '__module__' : 'file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:ServerSpeedResponse)
  })
_sym_db.RegisterMessage(ServerSpeedResponse)

ServerSpeedRequest = _reflection.GeneratedProtocolMessageType('ServerSpeedRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVERSPEEDREQUEST,
  '__module__' : 'file_transfer_pb2'
  # @@protoc_insertion_point(class_scope:ServerSpeedRequest)
  })
_sym_db.RegisterMessage(ServerSpeedRequest)

_FILETRANSFER = DESCRIPTOR.services_by_name['FileTransfer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=23
  _RESPONSE._serialized_end=60
  _REQUEST._serialized_start=62
  _REQUEST._serialized_end=104
  _SERVERSPEEDRESPONSE._serialized_start=106
  _SERVERSPEEDRESPONSE._serialized_end=147
  _SERVERSPEEDREQUEST._serialized_start=149
  _SERVERSPEEDREQUEST._serialized_end=186
  _FILETRANSFER._serialized_start=188
  _FILETRANSFER._serialized_end=305
# @@protoc_insertion_point(module_scope)
